import "../../../src/common/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useLocale } from "next-intl";
import Sidebar from "@/common/components/__organisms/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Amindi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = useLocale();

  return (
    <html lang={locale}>
      <body className={`${inter.className} bg-[#F6F6F6]`}>
        <div className="w-screen h-screen md:p-3 xxl:p-6 flex md:gap-3 xxl:gap-6">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
