export const citiesArray = [
    { En: "tbilisi", Ge: "თბილისი" },
    { En: "abastumani", Ge: "აბასთუმანი" },
    { En: "kutaisi", Ge: "ქუთაისი" },
    { En: "batumi", Ge: "ბათუმი" },
    { En: "bakuriani", Ge: "ბაკურიანი" },
    { En: "zestafoni", Ge: "ზესტაფონი" },
    { En: "zugdidi", Ge: "ზუგდიდი" },
    { En: "chiatura", Ge: "ჭიათურა" },
    { En: "ozurgeti", Ge: "ოზურგეთი" },
    { En: "kobuleti", Ge: "ქობულეთი" },
    { En: "gori", Ge: "გორი" },
    { En: "gudauri", Ge: "გუდაური" },
    { En: "sachkhere", Ge: "საჩხერე" },
    { En: "signagi", Ge: "სიღნაღი" },
    { En: "senaki", Ge: "სენაკი" },
    { En: "samtredia", Ge: "სამტრედია" },
    { En: "akhaltsikhe", Ge: "ახალციხე" },
    { En: "mestia", Ge: "მესტია" },
    { En: "gurjaani", Ge: "გურჯაანი" },
    { En: "khashuri", Ge: "ხაშური" },
    { En: "chokhatauri", Ge: "ჩოხატაური" },
    { En: "borjomi", Ge: "ბორჯომი" },
    { En: "sagarejo", Ge: "საგარეჯო" },
    { En: "lagodekhi", Ge: "ლაგოდეხი" },
    { En: "tianeti", Ge: "თიანეთი" },
    { En: "kharagauli", Ge: "ხარაგაული" },
    { En: "cxinvali", Ge: "ცხინვალი" },
    { En: "rustavi", Ge: "რუსთავი" },
    { En: "ureki", Ge: "ურეკი" },
    { En: "lanchkhuti", Ge: "ლანჩხუთი" },
    { En: "surami", Ge: "სურამი" },
    { En: "poti", Ge: "ფოთი" },
    { En: "oni", Ge: "ონი" },
    { En: "shekvetili", Ge: "შეკვეთილი" },
    { En: "marneuli", Ge: "მარნეული" },
    { En: "bolnisi", Ge: "ბოლნისი" },
    { En: "manglisi", Ge: "მანგლისი" },
    { En: "mcxeta", Ge: "მცხეთა" },
    { En: "gonio", Ge: "გონიო" },
    { En: "shatili", Ge: "შატილი" },
    { En: "shovi", Ge: "შოვი" },
    { En: "tsinandali", Ge: "წინანდალი" },
    { En: "khobi", Ge: "ხობი" },
    { En: "tskneti", Ge: "წყნეთი" },
    { En: "sioni", Ge: "სიონი" },
    { En: "sokhumi", Ge: "სოხუმი" },
    { En: "ushguli", Ge: "უშგული" },
    { En: "davit-gareji", Ge: "დავით-გარეჯი" },
    { En: "omalo", Ge: "ომალო" },
    { En: "axalkalaki", Ge: "ახალქალაქი" },
    { En: "martvili", Ge: "მარტვილი" },
    { En: "khoni", Ge: "ხონი" },
    { En: "anaklia", Ge: "ანაკლია" },
    { En: "adigeni", Ge: "ადიგენი" },
  ];

  export const weekDaysArray = [
    { En: "Monday", Ge: "ორშაბათი" },
    { En: "Tuesday", Ge: "სამშაბათი" },
    { En: "Wednesday", Ge: "ოთხშაბათი" },
    { En: "Thursday", Ge: "ხუთშაბათი" },
    { En: "Friday", Ge: "პარასკევი" },
    { En: "Saturday", Ge: "შაბათი" },
    { En: "Sunday", Ge: "კვირა" },

  ]
  export const monthsArray = [
    { En: "January", Ge: "იანვარი" },
    { En: "February", Ge: "თებერვალი" },
    { En: "March", Ge: "მარტი" },
    { En: "April", Ge: "აპრილი" },
    { En: "May", Ge: "მაისი" },
    { En: "June", Ge: "ივნისი" },
    { En: "July", Ge: "ივლისი" },
    { En: "August", Ge: "აგვისტო" },
    { En: "September", Ge: "სექტემბერი" },
    { En: "October", Ge: "ოქტომბერი" },
    { En: "November", Ge: "ნოემბერი" },
    { En: "December", Ge: "დეკემბერი" },
  ];

  export const weathersArray = [
    { En: "rainy", Ge: "წვიმა" },
    { En: "sunny", Ge: "მზიანი" },
    { En: "clear", Ge: "მოწმენდილი" },
    { En: "mostly clear", Ge: "უმეტესად მოწმენდილი" },
    { En: "partly sunny", Ge: "ნაწილობრივ მზიანი" },
    { En: "heavy cloudiness", Ge: "ნაწილობრივ ღრუბლიანი" },
    { En: "intermittently cloudy", Ge: "ძლიერი მოღრუბლულობა" },
    { En: "mostly cloudy", Ge: "პერიოდულად ღრუბლიანი" },
    { En: "mostly cloudy", Ge: "უმეტესად ღრუბლიანი" },
    { En: "mostly cloudy", Ge: "მეტესად ღრუბლიანი" },
    { En: "mostly sunny", Ge: "უმეტესად მზიანი" },
    { En: "partly sunny, light snow", Ge: "ნაწილობრივ მზიანი, სუსტი თოვლი" },
    { En: "light snow", Ge: "სუსტი თოვლი" },
    { En: "mostly cloudy, light snow", Ge: "უმეტესად ღრუბლიანი, სუსტი თოვლი" },
    { En: "mostly cloudy, snow", Ge: "უმეტესად ღრუბლიანი, თოვლი" },
    { En: "snow", Ge: "თოვლი" },
    { En: "pouring rain", Ge: "კოკისპირული წვიმა" },
    { En: "pouring rain, mostly cloudy", Ge: "კოკისპირული წვიმა, უმეტესად ღრუბლიანი" },
    { En: "cloudy", Ge: "ღრუბლიანი" },
    { En: "changeable cloudy", Ge: "ცვალებადი მოღრუბლულობა" },
    { En: "partly cloudy", Ge: "ნაწილობრივ ღრუბლიანი" },
    { En: "changeable cloudy", Ge: "ერიოდულად ღრუბლიანი" },
    { En: "changeable cloudy", Ge: "პერიოდულად ღრუბლიანი" },
    { En: "mist", Ge: "ბურუსი" },
    { En: "partly sunny, pouring rain", Ge: "ნაწილობრივ მზიანი კოკისპირული წვიმით" },
    { En: "partly cloudy, pouring rain", Ge: "ნაწილობრივ ღრუბლიანი, კოკისპირული წვიმა" },
    { En: "mostly cloudy, pouring rain", Ge: "უმეტესად ღრუბლიანი, კოკისპირული წვიმა" },
    { En: "thunderstorm", Ge: "ჭექა-ქუხილი" },
    { En: "mostly sunny, partly rain", Ge: "უმეტესად მზიანი, ნაწილობრივ წვიმა" },
    { En: "partly sunny, mostly rain", Ge: "ნაწილობრივ მზიანი, უმეტესად წვიმა" },
    { En: "frost", Ge: "ყინვა" },
    { En: "partly cloudy, thunderstorm", Ge: "ნაწილობრივ ღრუბლიანი, ჭექა-ქუხილი" },
    { En: "partly cloudy, thunderstorm", Ge: "ნაწილობრივ ღრუბლიანი, ჯექა-ქუხილი" },
  ];