export const citiesArray = [
  { En: "tbilisi", Ge: "თბილისი", Ru: "Тбилиси" },
  { En: "abastumani", Ge: "აბასთუმანი", Ru: "Абастумани" },
  { En: "kutaisi", Ge: "ქუთაისი", Ru: "Кутаиси" },
  { En: "batumi", Ge: "ბათუმი", Ru: "Батуми" },
  { En: "bakuriani", Ge: "ბაკურიანი", Ru: "Бакуриани" },
  { En: "zestafoni", Ge: "ზესტაფონი", Ru: "Зестафони" },
  { En: "zugdidi", Ge: "ზუგდიდი", Ru: "Зугдиди" },
  { En: "chiatura", Ge: "ჭიათურა", Ru: "Чиатура" },
  { En: "ozurgeti", Ge: "ოზურგეთი", Ru: "Озургети" },
  { En: "kobuleti", Ge: "ქობულეთი", Ru: "Кобулети" },
  { En: "gori", Ge: "გორი", Ru: "Гори" },
  { En: "gudauri", Ge: "გუდაური", Ru: "Гудаури" },
  { En: "sachkhere", Ge: "საჩხერე", Ru: "Сачхере" },
  { En: "signagi", Ge: "სიღნაღი", Ru: "Сигнахи" },
  { En: "senaki", Ge: "სენაკი", Ru: "Сенаки" },
  { En: "samtredia", Ge: "სამტრედია", Ru: "Самтредиа" },
  { En: "akhaltsikhe", Ge: "ახალციხე", Ru: "Ахалцихе" },
  { En: "mestia", Ge: "მესტია", Ru: "Местиа" },
  { En: "gurjaani", Ge: "გურჯაანი", Ru: "Гурджаани" },
  { En: "khashuri", Ge: "ხაშური", Ru: "Хашури" },
  { En: "chokhatauri", Ge: "ჩოხატაური", Ru: "Чохатаури" },
  { En: "borjomi", Ge: "ბორჯომი", Ru: "Боржоми" },
  { En: "sagarejo", Ge: "საგარეჯო", Ru: "Сагареджо" },
  { En: "lagodekhi", Ge: "ლაგოდეხი", Ru: "Лагодехи" },
  { En: "tianeti", Ge: "თიანეთი", Ru: "Тианети" },
  { En: "kharagauli", Ge: "ხარაგაული", Ru: "Харагаули" },
  { En: "cxinvali", Ge: "ცხინვალი", Ru: "Цхинвали" },
  { En: "rustavi", Ge: "რუსთავი", Ru: "Рустави" },
  { En: "ureki", Ge: "ურეკი", Ru: "Уреки" },
  { En: "lanchkhuti", Ge: "ლანჩხუთი", Ru: "Ланчхути" },
  { En: "surami", Ge: "სურამი", Ru: "Сурами" },
  { En: "poti", Ge: "ფოთი", Ru: "Поти" },
  { En: "oni", Ge: "ონი", Ru: "Они" },
  { En: "shekvetili", Ge: "შეკვეთილი", Ru: "Шекветили" },
  { En: "marneuli", Ge: "მარნეული", Ru: "Марнеули" },
  { En: "bolnisi", Ge: "ბოლნისი", Ru: "Болниси" },
  { En: "manglisi", Ge: "მანგლისი", Ru: "Манглиси" },
  { En: "mcxeta", Ge: "მცხეთა", Ru: "Мцхета" },
  { En: "gonio", Ge: "გონიო", Ru: "Гонио" },
  { En: "shatili", Ge: "შატილი", Ru: "Шатили" },
  { En: "shovi", Ge: "შოვი", Ru: "Шови" },
  { En: "tsinandali", Ge: "წინანდალი", Ru: "Цинандали" },
  { En: "khobi", Ge: "ხობი", Ru: "Хоби" },
  { En: "tskneti", Ge: "წყნეთი", Ru: "Цкнети" },
  { En: "sioni", Ge: "სიონი", Ru: "Сиони" },
  { En: "sokhumi", Ge: "სოხუმი", Ru: "Сухуми" },
  { En: "ushguli", Ge: "უშგული", Ru: "Ушгули" },
  { En: "davit-gareji", Ge: "დავით-გარეჯი", Ru: "Давид-Гарейский" },
  { En: "omalo", Ge: "ომალო", Ru: "Омало" },
  { En: "axalkalaki", Ge: "ახალქალაქი", Ru: "Ахалкалаки" },
  { En: "martvili", Ge: "მარტვილი", Ru: "Мартвили" },
  { En: "khoni", Ge: "ხონი", Ru: "Хони" },
  { En: "anaklia", Ge: "ანაკლია", Ru: "Анаклия" },
  { En: "adigeni", Ge: "ადიგენი", Ru: "Адигени" },
];

export const weekDaysArray = [
  { En: "Monday", Ge: "ორშაბათი", Ru: "Понедельник" },
  { En: "Tuesday", Ge: "სამშაბათი", Ru: "Вторник" },
  { En: "Wednesday", Ge: "ოთხშაბათი", Ru: "Среда" },
  { En: "Thursday", Ge: "ხუთშაბათი", Ru: "Четверг" },
  { En: "Friday", Ge: "პარასკევი", Ru: "Пятница" },
  { En: "Saturday", Ge: "შაბათი", Ru: "Суббота" },
  { En: "Sunday", Ge: "კვირა", Ru: "Воскресенье" },
];

export const monthsArray = [
  { En: "January", Ge: "იანვარი", Ru: "Январь" },
  { En: "February", Ge: "თებერვალი", Ru: "Февраль" },
  { En: "March", Ge: "მარტი", Ru: "Март" },
  { En: "April", Ge: "აპრილი", Ru: "Апрель" },
  { En: "May", Ge: "მაისი", Ru: "Май" },
  { En: "June", Ge: "ივნისი", Ru: "Июнь" },
  { En: "July", Ge: "ივლისი", Ru: "Июль" },
  { En: "August", Ge: "აგვისტო", Ru: "Август" },
  { En: "September", Ge: "სექტემბერი", Ru: "Сентябрь" },
  { En: "October", Ge: "ოქტომბერი", Ru: "Октябрь" },
  { En: "November", Ge: "ნოემბერი", Ru: "Ноябрь" },
  { En: "December", Ge: "დეკემბერი", Ru: "Декабрь" },
];

export const weathersArray = [
  { En: "rainy", Ge: "წვიმა", Ru: "Дождливо" },
  { En: "sunny", Ge: "მზიანი", Ru: "Солнечно" },
  { En: "clear", Ge: "მოწმენდილი", Ru: "Ясно" },
  { En: "mostly clear", Ge: "უმეტესად მოწმენდილი", Ru: "В основном ясно" },
  { En: "partly sunny", Ge: "ნაწილობრივ მზიანი", Ru: "Переменная облачность" },
  { En: "heavy cloudiness", Ge: "ნაწილობრივ ღრუბლიანი", Ru: "Пасмурно" },
  {
    En: "intermittently cloudy",
    Ge: "ძლიერი მოღრუბლულობა",
    Ru: "Переменная облачность",
  },
  { En: "mostly cloudy", Ge: "პერიოდულად ღრუბლიანი", Ru: "В основном облачно" },
  { En: "mostly cloudy", Ge: "უმეტესად ღრუბლიანი", Ru: "В основном облачно" },
  { En: "mostly cloudy", Ge: "მეტესად ღრუბლიანი", Ru: "В основном облачно" },
  { En: "mostly sunny", Ge: "უმეტესად მზიანი", Ru: "В основном солнечно" },
  {
    En: "partly sunny, light snow",
    Ge: "ნაწილობრივ მზიანი, სუსტი თოვლი",
    Ru: "Переменная облачность, легкий снег",
  },
  { En: "light snow", Ge: "სუსტი თოვლი", Ru: "Легкий снег" },
  {
    En: "mostly cloudy, light snow",
    Ge: "უმეტესად ღრუბლიანი, სუსტი თოვლი",
    Ru: "В основном облачно, легкий снег",
  },
  {
    En: "mostly cloudy, snow",
    Ge: "უმეტესად ღრუბლიანი, თოვლი",
    Ru: "В основном облачно, снег",
  },
  { En: "snow", Ge: "თოვლი", Ru: "Снег" },
  { En: "pouring rain", Ge: "კოკისპირული წვიმა", Ru: "Проливной дождь" },
  {
    En: "pouring rain, mostly cloudy",
    Ge: "კოკისპირული წვიმა, უმეტესად ღრუბლიანი",
    Ru: "Проливной дождь, в основном облачно",
  },
  { En: "cloudy", Ge: "ღრუბლიანი", Ru: "Облачно" },
  {
    En: "changeable cloudy",
    Ge: "ცვალებადი მოღრუბლულობა",
    Ru: "Изменчивая облачность",
  },
  {
    En: "partly cloudy",
    Ge: "ნაწილობრივ ღრუბლიანი",
    Ru: "Переменная облачность",
  },
  {
    En: "changeable cloudy",
    Ge: "ერიოდულად ღრუბლიანი",
    Ru: "Изменчивая облачность",
  },
  {
    En: "changeable cloudy",
    Ge: "პერიოდულად ღრუბლიანი",
    Ru: "Изменчивая облачность",
  },
  { En: "mist", Ge: "ბურუსი", Ru: "Туман" },
  {
    En: "partly sunny, pouring rain",
    Ge: "ნაწილობრივ მზიანი კოკისპირული წვიმით",
    Ru: "Переменная облачность, проливной дождь",
  },
  {
    En: "partly cloudy, pouring rain",
    Ge: "ნაწილობრივ ღრუბლიანი, კოკისპირული წვიმა",
    Ru: "Переменная облачность, проливной дождь",
  },
  {
    En: "mostly cloudy, pouring rain",
    Ge: "უმეტესად ღრუბლიანი, კოკისპირული წვიმა",
    Ru: "В основном облачно, проливной дождь",
  },
  { En: "thunderstorm", Ge: "ჭექა-ქუხილი", Ru: "Гроза" },
  {
    En: "mostly sunny, partly rain",
    Ge: "უმეტესად მზიანი, ნაწილობრივ წვიმა",
    Ru: "В основном солнечно, периодически дождь",
  },
  {
    En: "partly sunny, mostly rain",
    Ge: "ნაწილობრივ მზიანი, უმეტესად წვიმა",
    Ru: "Переменная облачность, в основном дождь",
  },
  { En: "frost", Ge: "ყინვა", Ru: "Мороз" },
  {
    En: "partly cloudy, thunderstorm",
    Ge: "ნაწილობრივ ღრუბლიანი, ჭექა-ქუხილი",
    Ru: "Переменная облачность, гроза",
  },
  {
    En: "partly cloudy, thunderstorm",
    Ge: "ნაწილობრივ ღრუბლიანი, ჯექა-ქუხილი",
    Ru: "Переменная облачность, гроза",
  },
];
